[default_profile]
address = "https://ams-vpn-cluster.cisco.com/ssl"
user_group = ""
name = ""
on_disconnect = "~/.ssh/kill-ssh-control-masters.sh"

[auto_fill_rules]
[[auto_fill_rules."https://*"]]
selector = "div[id=passwordError]"
action = "stop"

[[auto_fill_rules."https://*"]]
selector = "input[type=email]"
fill = "username"

[[auto_fill_rules."https://*"]]
selector = "input[type=password]"
fill = "password"

[[auto_fill_rules."https://*"]]
selector = "input[type=submit]"
action = "click"

