# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6e65f731-a7dc-4e30-9101-9d3539eac5dc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1fca8b6d-fc9c-44e9-a3b0-56bf162f8f43".device = "/dev/disk/by-uuid/1fca8b6d-fc9c-44e9-a3b0-56bf162f8f43";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/E567-3965";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/13559fe6-63ae-46e6-a74f-e82ba11941f9"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
