#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = 'gruvbox'
    background = 'dark'
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = 'arrow'
    statusline_inactive_separator = 'bar'
    buffer_index_type = 4
    windows_index_type = 3
    # enable_tabline_filetype_icon = true
    # enable_tabline_ft_icon = true
    enable_os_fileformat_icon = true
    enable_statusline_display_mode = true
    enable_statusline_mode = true

    # jherland's additions
    # enable_debug = true
    default_indent = 4
    expandtab = true
    # relativenumber = false
    max_column = 80
    sidebar_width = 40
    enable_powerline_fonts = true
    statusline_unicode_symbols = false
    # statusline_right_sections 'whitespace'
    error_symbol = 'X'
    warning_symbol = '!'
    info_symbol = 'i'
    github_username = 'jherland'
    enable_vimfiler_welcome = true
    enable_vimfiler_gitstatus = true
    enable_vimfiler_filetypeicon = true
    filetree_direction = 'right'
    autocomplete_method = 'asyncomplete'
    # enable_neomake = 0
    # enable_ale = 1
    # enable_ycm = 1
    auto_disable_touchpad = true
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'

    disabled_plugins = []
    custom_plugins = []

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = 'complete'
auto-completion-tab-key-behavior = 'cycle'

# [[layers]]
# name = 'shell'
# default_position = 'left'
# default_height = 30

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'git'

[[layers]]
name = 'tools'

[[layers]]
name = 'denite'

[[layers]]
name = 'default'

# [[layers]]
# name = 'cscope'

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#haskell'

[[layers]]
name = 'lang#python'
format-on-save = false
